### ISSUE TITLE
$this->imageService not available in 11.3

### ISSUE THREAD

**Issue by sir-gawain** [sitegeist/sms-responsive-images#81]
replace it with $this->getImageService()

**Comment by Hobokens** [comment]
Hi,
thanks for the hint. Do I have to replace it everywhere?

**Comment by s2b** [comment]
Thank you for the bug report. In order to stay compatible with TYPO3 10, just replacing the variable isn't enough. I'm not sure when I'll find the time to address this, but until then I would be happy to review/accept pull requests.

**Comment by sir-gawain** [comment]
the change was done in commit https://github.com/TYPO3/typo3/commit/7e6a9da5b45a19b6504de76f67a0efaf5d5ff5fa
i think the easiest fix would be to simply copy the changes from this commit. The class ImageService also exists in T3 10 and only the injection changed, so this should be fine.

**Comment by s2b** [comment]
Seems like this will be changed/fixed again in TYPO3 11.4. So I will probably not apply my bugfix in the referenced pull request.

https://review.typo3.org/c/Packages/TYPO3.CMS/+/70245

**Comment by s2b** [comment]
Should be fixed with 11.4, worked in my local testing environment.

**Comment by sir-gawain** [comment]
Does it work now? I updated the project to 11.4 and the error is still there.

**Comment by s2b** [comment]
We checked again with a local test installation, it worked fine in our case. If the problem persists, could you be more specific and create a new issue for that?
